export type ValidSkills =
  | "Next.js"
  | "React"
  | "GraphQL"
  | "express.js"
  | "Node.js"
  | "MongoDB"
  | "Typescript"
  | "Javascript"
  | "HTML 5"
  | "CSS 3"
  | "Redux"
  | "Socket.io"
  | "Tailwind CSS"
  | "AWS"
  | "Bootstrap"
  | "Google Cloud"
  | "Azure"
  | "Google Auth"
  | "MySQL"
  | "Python"
  | "Docker"
  | "Kubernetes"
  | "PostgreSQL"
  | "Redis"
  | "Git"
  | "CI/CD"
  | "Jenkins"
  | "Django"
  | "Sass"
  | "Firebase"
  | "Figma"
  | "Storybook"
  | "Vercel"
  | "TensorFlow"
  | "PyTorch"
  | "Laravel"
  | "PHP"
  | "Flask"
  | "FastAPI"
  | "SQL"
  | "NoSQL"
  | "Framer Motion";

export type ValidCategory =
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev";

export type ValidExpType = "Personal" | "Professional";

export type ValidPages =
  | "home"
  | "skills"
  | "projects"
  | "experience"
  | "education"
  | "cv";
