export const siteConfig = {
  name: "Adesh Kumar Sharma | Developer Portfolio",
  authorName: "Adesh Kumar Sharma",
  username: "Adesh-Kumar-Sharma",
  description:
    "Adesh Kumar Sharma's portfolio - A modern, responsive Next.js portfolio for developers. This open-source template can be customized to showcase your own skills, projects, and professional experience.",
  url: "https://portfolio-adesh.vercel.app",
  links: {
    github: "https://github.com/Adesh-Kumar-Sharma",
  },
  ogImage: "https://portfolio-adesh.vercel.app/profile-img.jpg",
  iconIco:
    "https://res.cloudinary.com/dowwkeqlx/image/upload/v1758174052/adesh-favicon.ico",
  logoIcon:
    "https://res.cloudinary.com/dowwkeqlx/image/upload/v1758174052/adesh-logo.png",
  keywords: [
    "Adesh Kumar Sharma",
    "Full Stack Developer",
    "Web Developer Portfolio",
    "Next.js portfolio template",
    "React portfolio template",
    "Developer portfolio template",
    "Portfolio website template",
    "Next.js template",
    "Modern portfolio website",
    "Frontend developer portfolio",
    "Full stack developer portfolio",
    "Open source portfolio template",
    "Web developer portfolio template",
    "Responsive portfolio template",
    "React.js portfolio",
    "Tailwind CSS portfolio",
    "Developer showcase template",
    "Free portfolio template",
    "Next.js 13 template",
    "Shadcn UI template",
    "Career timeline template",
    "Portfolio with dark mode",
    "GitHub portfolio template",
  ],
};
